### ISSUE TITLE
Error after latest update: TypeError: Cannot read properties of undefined (reading 'tokenizePlaceholders')

### ISSUE THREAD

**Issue by akshayKhot** [basecamp/lexxy#489]
Hi,

First of all, great work on the Lexxy editor. Been using it for the past month and very happy with it.

After updating to the latest version of the gem today, I noticed that syntax highlighting stopped working. Calling `highlightAll()` from the Stimulus controller that handles highlighting now raises an error:

<img width="584" height="194" alt="Image" src="https://github.com/user-attachments/assets/77fc68cb-0240-4229-ab80-d900dd16bf1e" />

While reading more on it, I came across [this old issue](https://github.com/PrismJS/prism/issues/1400) in the PrismJS repository, specifically, [this comment](https://github.com/PrismJS/prism/issues/1400#issuecomment-485847919):

> you have to include `prismjs/components/prism-markup-templating.js` before `prismjs/components/prism-php.js` to fix the error in this issue.

Looks like [PR #468](https://github.com/basecamp/lexxy/pull/468/) added PHP to the list of available languages last week, which may have caused this issue?

Thanks,
Akshay

**Comment by jorgemanrubia** [comment]
@akshayKhot thanks for the report, looking into this one.

**Comment by jorgemanrubia** [comment]
This should be fixed in https://github.com/basecamp/lexxy/releases/tag/v0.1.24.beta

**Comment by akshayKhot** [comment]
Thanks @jorgemanrubia. Is the latest beta release (v0.1.24.beta) not pushed to RubyGems? There I still see 0.1.23.beta as the latest version.

**Comment by jorgemanrubia** [comment]
Sorry, it seems the gem publication failed and I did not notice. It is there now: https://rubygems.org/gems/lexxy?locale=en

**Comment by akshayKhot** [comment]
Syntax highlighting is working as expected now. Thanks @jorgemanrubia !
