### ISSUE TITLE
Removing attachments with backspace is broken: '"_cachedNodes" is read-only'

### ISSUE THREAD

**Issue by OtherCroissant** [basecamp/lexxy#494]
I have setup the prompts for selecting things with the hashtag (#) in a lexxy editor. Implementing this was super simple! Very nice feature!

Only stumbled upon an error when I wanted to remove the attachment by using the backspace. The steps:

<img width="699" height="254" alt="Image" src="https://github.com/user-attachments/assets/3098b78d-2a68-407c-ae11-7cf35245f80c" />

`<backspace>`

<img width="679" height="234" alt="Image" src="https://github.com/user-attachments/assets/fe5448fc-f07c-4f59-953a-768c39b5f502" />

`<backspace>`

JS Error: `"_cachedNodes" is read-only`

<img width="910" height="604" alt="Image" src="https://github.com/user-attachments/assets/2de4ee33-951f-493b-baff-2ca8234723d6" />

Or in text:

```
Uncaught TypeError: "_cachedNodes" is read-only
    getNodes http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:48210
    node_modules 37signals/lexxy/dist/lexxy.esm.js/deleteSelectedNodes/<@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:2733
    $processNestedUpdates http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:51022
    $beginUpdate http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:51072
    updateEditorSync http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:51153
    triggerCommandListeners http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:50949
    dispatchCommand http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:54163
    onKeyDown http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:45188
    eventHandler http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:45346
    addRootElementEvents http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:45377
    setRootElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:53020
    #createEditor http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:3606
    connectedCallback http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:3464
    renderElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9696
    loadFrameElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9723
    node_modules hotwired/turbo/dist/turbo.es2017-esm.js/render/<@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9712
    preservingPermanentElements http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9534
    preservingPermanentElements http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9635
    render http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9711
    renderSnapshot http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9340
    render http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9300
    #loadFrameResponse http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13850
    loadResponse http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13670
    requestSucceededWithResponse http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13745
    receive http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8663
    perform http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8640
    node_modules hotwired/turbo/dist/turbo.es2017-esm.js/#visit/<@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13872
    #visit http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13866
    #loadSourceURL http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13651
    elementAppearedInViewport http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13685
    intersect http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8778
    AppearanceObserver http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8758
    FrameController http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13578
    FrameElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:7873
    node_modules hotwired/turbo/dist/turbo.es2017-esm.js@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:14394
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    node_modules hotwired/turbo-rails/app/javascript/turbo/cable_stream_source_element.js@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:7488
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    node_modules hotwired/turbo-rails/app/javascript/turbo/index.js@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:7634
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    js http://localhost:3002/packs/js/application.js:1083
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    webpackContext http://localhost:3002/packs/js/application.js:74
    definitionForModuleWithContextAndKey http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:4829
    node_modules hotwired/stimulus-webpack-helpers/dist/stimulus-webpack-helpers.js/definitionsFromContext/<@http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:4823
    definitionsFromContext http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:4823
    js http://localhost:3002/packs/js/application.js:362
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    js http://localhost:3002/packs/js/application.js:1795
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    __webpack_exec__ http://localhost:3002/packs/js/application.js:1846
    <anonymous> http://localhost:3002/packs/js/application.js:1847
    O http://localhost:3002/packs/js/runtime.js:67
    <anonymous> http://localhost:3002/packs/js/application.js:1848
    webpackJsonpCallback http://localhost:3002/packs/js/runtime.js:312
    <anonymous> http://localhost:3002/packs/js/application.js:1
vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:48210:7
    getNodes http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:48210
    deleteSelectedNodes http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:2733
    $processNestedUpdates http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:51022
    $beginUpdate http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:51072
    updateEditorSync http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:51153
    triggerCommandListeners http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:50949
    dispatchCommand http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:54163
    onKeyDown http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:45188
    eventHandler http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:45346
    (Async: EventListener.handleEvent)
    addRootElementEvents http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:45377
    setRootElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:53020
    #createEditor http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:3606
    connectedCallback http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:3464
    renderElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9696
    loadFrameElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9723
    render http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9712
    preservingPermanentElements http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9534
    preservingPermanentElements http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9635
    render http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9711
    InterpretGeneratorResume self-hosted:1332
    AsyncFunctionNext self-hosted:800
    (Async: async)
    renderSnapshot http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9340
    render http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:9300
    InterpretGeneratorResume self-hosted:1332
    AsyncFunctionNext self-hosted:800
    (Async: async)
    #loadFrameResponse http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13850
    InterpretGeneratorResume self-hosted:1332
    AsyncFunctionNext self-hosted:800
    (Async: async)
    loadResponse http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13670
    InterpretGeneratorResume self-hosted:1332
    AsyncFunctionNext self-hosted:800
    (Async: async)
    requestSucceededWithResponse http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13745
    receive http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8663
    perform http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8640
    InterpretGeneratorResume self-hosted:1332
    AsyncFunctionNext self-hosted:800
    (Async: async)
    visit http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13872
    #visit http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13866
    #loadSourceURL http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13651
    elementAppearedInViewport http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13685
    intersect http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8778
    (Async: IntersectionCallback)
    AppearanceObserver http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:8758
    FrameController http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:13578
    FrameElement http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:7873
    js http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:14394
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    js http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:7488
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    js http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:7634
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    js http://localhost:3002/packs/js/application.js:1083
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    webpackContext http://localhost:3002/packs/js/application.js:74
    definitionForModuleWithContextAndKey http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:4829
    definitionsFromContext http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:4823
    map self-hosted:175
    definitionsFromContext http://localhost:3002/packs/js/vendors-node_modules_37signals_lexxy_dist_lexxy_esm_js-node_modules_hotwired_stimulus-webpack-f44598.js:4823
    js http://localhost:3002/packs/js/application.js:362
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    js http://localhost:3002/packs/js/application.js:1795
    __webpack_require__ http://localhost:3002/packs/js/runtime.js:23
    __webpack_exec__ http://localhost:3002/packs/js/application.js:1846
    <anoniem> http://localhost:3002/packs/js/application.js:1847
    O http://localhost:3002/packs/js/runtime.js:67
    <anoniem> http://localhost:3002/packs/js/application.js:1848
    webpackJsonpCallback http://localhost:3002/packs/js/runtime.js:312
    <anoniem> http://localhost:3002/packs/js/application.js:1
```

Maybe for the author of the prompts, this would be an easy fix. For me to dive into this to suggest a PR would be quite a challenge (but let me know and I will try it).

**Comment by jorgemanrubia** [comment]
I think this was fixed in https://github.com/basecamp/lexxy/releases/tag/v0.1.24.beta. Please let me know if it wasn't.

**Comment by OtherCroissant** [comment]
@jorgemanrubia I am afraid this is still broken in v0.1.24.beta. Not only removing attachments with backspaces breaks with the _cacheNodes error, also removing elements like a divider.

<img width="570" height="261" alt="Image" src="https://github.com/user-attachments/assets/2b090509-44df-4ab7-8c74-b808710f9b9a" />
